### PR TITLE
Handle when a git commit has no message

### LINKED ISSUE #866: Commit view doesn't work with empty commit message
### Description

Commit view doesn't work with empty commit message.

### Neovim version

```
λ nvim --version
NVIM v0.10.0-dev-248305c
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

```
Linux root 6.1.55 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep 23 09:11:13 UTC 2023 x86_64 GNU/Linux
```

### Steps to reproduce

Commit with empty message
```
git commit -m --allow-empty-message ""
```

image

Open commit view on that commit.
It prints error

### Expected behavior

Should work as normal.

### Actual behavior

```
|| Error executing vim.schedule lua callback: ...pack/bundle/opt/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...m/site/pack/bundle/opt/neogit/lua/neogit/lib/git/log.lua:58: Failed to parse line: index e69de29..64a8729 100644
|| stack traceback:
|| 	[C]: in function 'error'
|| 	...pack/bundle/opt/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
|| 	...pack/bundle/opt/plenary.nvim/lua/plenary/async/async.lua:45: in function <...pack/bundle/opt/plenary.nvim/lua/plenary/async/async.lua:44>
```

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "NeogitOrg/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

### PR DESCRIPTION
**Pull request by CKolkey**
Fixes #866 

I had no idea you could add a commit without a message. Wild.

### CODE REVIEW

File: tests/init.lua [hunk 1]
```diff
@@ -22,7 +22,10 @@ else
...
-  minimal_init = "tests/minimal_init.lua",
-  sequential = true,
-})
+require("plenary.test_harness").test_directory(
+  os.getenv("TEST_FILES") == "" and "tests/specs" or os.getenv("TEST_FILES"),
+  {
+    minimal_init = "tests/minimal_init.lua",
+    sequential = true,
+  }
+)
```
Comment (CKolkey) [inline tests/init.lua:31]: @ten3roberts We can now just test select files via `TEST_FILE=pattern make test` :)
